export const REQUEST_POST_GAME = 'REQUEST_POST_GAME';
export const SUCCESS_POST_GAME = 'SUCCESS_POST_GAME';
export const FAILED_POST_GAME = 'FAILED_POST_GAME';

export const REQUEST_FETCH_GAMES = 'REQUEST_FETCH_GAMES';
export const SUCCESS_FETCH_GAMES = 'SUCCESS_FETCH_GAMES';
export const FAILED_FETCH_GAMES = 'FAILED_FETCH_GAMES';