# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac6abff4d70d784e58733c74f82df8c68062b5adfe57fec102e7d433a9d86bf450040c466f040509fda15a3e347121d421526926a93bf3448d269f447819423a

test:
  secret_key_base: 21950cb21c5d6bb455b6afa917864153fa7f3c8570636f6d7be986423129afc2757280f2e11b6c94d287149687ecae52fd67e6e775ec02d7744218d320343c87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
